# Site settings
title: CSAL4243: Introduction to Machine Learning
email: mudassir.khan@ucp.edu.pk
description: "Course materials and notes for UCP class CSAL4243: Introduction to Machine Learning."
baseurl: ""
url: "https://w4zir.github.io/ml17s/"
twitter_username: MmkWazir
github_username:  w4zir

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
